// react-test/src/Editor.jsx
import React, { useEffect, useRef } from 'react';
import { initMarkdownEditor, renderMarkdownEditor } from '@cannonui/md-edit';

const MarkdownEditorComponent = ({ value = '' }) => {
  const editorContainer = useRef(null);

  const html = renderMarkdownEditor(value);
  useEffect(() => {
    if (editorContainer.current) {
      editorContainer.current.innerHTML = html;
      initMarkdownEditor(editorContainer.current);
    }
  }, [value]); // Re-run this effect if 'value' changes

  return (
    <div ref={editorContainer}></div>
  );
};

export default MarkdownEditorComponent;

// vue-test/src/components/Editor.vue
<!-- MarkdownEditorComponent.vue -->

<template>
  <div ref="editorContainer"></div>
</template>

<script setup>
// import { initMarkdownEditor, renderMarkdownEditor } from 'md-edit';
import { initMarkdownEditor, renderMarkdownEditor } from '@cannonui/md-edit';

import { ref, onMounted } from 'vue';
const props = defineProps({
  value: {
    type: String,
    default: '',
  },
});
const editorContainer = ref(null);
const html = renderMarkdownEditor(props.value);
onMounted(() => {
  editorContainer.value.innerHTML = html;
  initMarkdownEditor(editorContainer.value);
});
</script>
